### ISSUE TITLE
error when npm start

### ISSUE THREAD

**Issue by Alexis374** [react-component/m-date-picker#35]
git clone this repo, version: 6.0.0-alpha.5
run npm start,shows this:

Module build failed: TypeError: /Users/enniu/code/m-date-picker/src/index.tsx: Cannot read property 'indexOf' of undefined
    at Object.relative (/Users/enniu/code/m-date-picker/node_modules/source-map/lib/util.js:206:15)
    at BasicSourceMapConsumer.SourceMapConsumer_generatedPositionFor [as generatedPositionFor] (/Users/enniu/code/m-date-picker/node_modules/source-map/lib/source-map-consumer.js:731:21)
    at /Users/enniu/code/m-date-picker/node_modules/babel-core/lib/transformation/file/index.js:461:51
    at Array.forEach (native)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/enniu/code/m-date-picker/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at File.mergeSourceMap (/Users/enniu/code/m-date-picker/node_modules/babel-core/lib/transformation/file/index.js:460:24)
    at File.generate (/Users/enniu/code/m-date-picker/node_modules/babel-core/lib/transformation/file/index.js:719:25)
    at File.transform (/Users/enniu/code/m-date-picker/node_modules/babel-core/lib/transformation/file/index.js:554:17)
    at /Users/enniu/code/m-date-picker/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/Users/enniu/code/m-date-picker/node_modules/babel-core/lib/transformation/file/index.js:564:16)
 @ ./examples/simple.tsx 27:13-36
 @ multi ./examples/simple.tsx

**Comment by silentcloud** [comment]
没能重现
